pyinstaller --noconsole "kwCalcGQ.py" ^
--icon="class_x24.ico" ^
--clean ^
--workpath="C:\Users\ichet\YandexDisk\MyApps\MyPreDists\NewBuilds" ^
--distpath="C:\Users\ichet\YandexDisk\MyApps\MyPreDists\NewDists" ^
--add-data="antStepClimaData.txt;." ^
--add-data="class_x24.ico;." ^
--add-data="class_x24.png;." ^
--add-data="Hack-Regular.ttf;." ^
--add-data="matplotlibrc;." ^
--add-data="splitter.png;." ^
--add-data="splitter_pressed.png;." ^
--add-data="splitter_pressed_vertical.png;." ^
--add-data="splitter_vertical.png;." ^
--add-data="ww_style.css;." ^
--add-data="DSTU-H_B_V.1.1-27_2010.xlsx;." ^
--upx-dir="C:\Users\ichet\Dropbox\MyApps\py_to_utils\upx394w"